name = "react-native-backend"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "e31df8959f3a5ef85ea543dd630aeb54"

[[d1_databases]]
binding = "DB"
database_name = "react-native-db"
database_id = "ba3b238f-985c-438d-adeb-ac8e31e5f71a"
migrations_dir = "migrations"
